Adding support for AWS IAM based authentication
mgmonteleone/python-atlasapi pull request #65
Opened 2022-02-07 15:21 UTC by JohnPreston

Adding support for AWS IAM Authentication, as per
https://docs.atlas.mongodb.com/reference/api/database-users-create-a-user/

2022-02-07 17:37 UTC, JohnPreston commented
Note: delete for IAM user does not work due to db is named `$external` which the api_settings is not catering for atm

2022-03-20 22:32 UTC, mgmonteleone commented
Thanks @JohnPreston for submitting this, I will review this week.

2022-03-21 00:38 UTC, mgmonteleone requested changes
I have updated this change to use an Enum for safety.

Please see https://github.com/mgmonteleone/python-atlasapi/commit/0f30dfb63464c03d80aa8c79abeb3802b4ca7497

for my suggested changes. If you could merge that in to your PR, or create a new one, I will release that with 0.13.3

2022-03-21 00:42 UTC, mgmonteleone commented
Note: had to fix a typo in that commit. Fixup is in https://github.com/mgmonteleone/python-atlasapi/commit/0d9703f2fca0651a1a36182f975bd1fadbb4997f

2022-04-13 03:49 UTC, closed without merging